# Site settings:
title: Tammer IT Solutions
description: Sebastiaan Tammer is an Utrecht-based freelancer with a focus on Cloud, Linux, Automation and Security.

# Build settings:
markdown: kramdown
remote_theme: tammert/hacker
